In [57]:
import numpy as np
import random

In [48]:
def KRR_function(X,y,z):
    return (X-3)**2+(y-1)**2+z**2

In [53]:
def create_hyperparams_grid(X,y,z):
    graph_x = []
    graph_y = []
    graph_z = []
    graph_result=[]
    for alpha_value in X:
        graph_x_row = []
        graph_y_row = []
        graph_z_row = []
        graph_result_row = []
        for gamma_value in y:
            for beta_value in z:
                rmse = KRR_function(alpha_value,gamma_value,beta_value)
                graph_x_row.append(alpha_value)
                graph_y_row.append(gamma_value)
                graph_z_row.append(beta_value)
                graph_result_row.append(rmse)
            graph_x.append(graph_x_row)
            graph_y.append(graph_y_row)
            graph_z.append(graph_z_row)
            graph_result.append(graph_result_row)
    graph_x=np.array(graph_x)
    graph_y=np.array(graph_y)
    graph_z=np.array(graph_z)
    graph_result=np.array(graph_result)
    min_result = np.min(graph_result)
    pos_min_result = np.argwhere(graph_result == np.min(graph_result))[0]
    print('Minimum RMSE: %.4f' %(min_result))
    print('Optimum alpha: %f' %(graph_x[pos_min_result[0],pos_min_result[1]]))
    print('Optimum gamma: %f' %(graph_y[pos_min_result[0],pos_min_result[1]]))
    print('Optimum beta: %f' %(graph_z[pos_min_result[0],pos_min_result[1]]))
    return graph_x,graph_y,graph_z,graph_result

In [55]:
x1=np.arange(-20,20,1)
x2=np.arange(-10,10,1)
x3=np.arange(-10,10,1)

In [56]:
create_hyperparams_grid(x1,x2,x3)

Minimum RMSE: 0.0000
Optimum alpha: 3.000000
Optimum gamma: 1.000000
Optimum beta: 0.000000


(array([[-20, -20, -20, ..., -20, -20, -20],
        [-20, -20, -20, ..., -20, -20, -20],
        [-20, -20, -20, ..., -20, -20, -20],
        ...,
        [ 19,  19,  19, ...,  19,  19,  19],
        [ 19,  19,  19, ...,  19,  19,  19],
        [ 19,  19,  19, ...,  19,  19,  19]]),
 array([[-10, -10, -10, ...,   9,   9,   9],
        [-10, -10, -10, ...,   9,   9,   9],
        [-10, -10, -10, ...,   9,   9,   9],
        ...,
        [-10, -10, -10, ...,   9,   9,   9],
        [-10, -10, -10, ...,   9,   9,   9],
        [-10, -10, -10, ...,   9,   9,   9]]),
 array([[-10,  -9,  -8, ...,   7,   8,   9],
        [-10,  -9,  -8, ...,   7,   8,   9],
        [-10,  -9,  -8, ...,   7,   8,   9],
        ...,
        [-10,  -9,  -8, ...,   7,   8,   9],
        [-10,  -9,  -8, ...,   7,   8,   9],
        [-10,  -9,  -8, ...,   7,   8,   9]]),
 array([[750, 731, 714, ..., 642, 657, 674],
        [750, 731, 714, ..., 642, 657, 674],
        [750, 731, 714, ..., 642, 657, 674],
        ..